1. 브랜드
CREATE TABLE BRAND (
    BRANDID        NUMBER           PRIMARY KEY,
    BRANDNAME      VARCHAR2(100)    NOT NULL,
    COUNTRY        VARCHAR2(100), 
    ORIGIN         VARCHAR2(50),             
    BRANDINFO      VARCHAR2(500)

);
CREATE SEQUENCE BRAND_SEQ 
START WITH 1 INCREMENT BY 1
NOCACHE;



2. 사료
--2.푸드 (FK) BRANDID : BFAND(BRANDID)
CREATE TABLE PETFOOD (
    FOODID          NUMBER          PRIMARY KEY,
    FOODNAME        VARCHAR2(100)   NOT NULL,
    BRANDID         NUMBER          NOT NULL,
    MAININGREDIENT  VARCHAR2(200)   NOT NULL,
    PETTYPEID       NUMBER           DEFAULT 1,
    PETTYPENAME     VARCHAR2(255)    DEFAULT '고양이',
    CATEGORY        VARCHAR2(50)    NOT NULL,
    PETAGEGROUP     VARCHAR2(50),
    ISGRAINFREE     CHAR(1)         CHECK (UPPER(ISGRAINFREE) IN ('Y','N')),
    CALORIE         NUMBER(5,1),
    FOODTYPE        VARCHAR2(20) DEFAULT '습식',
    FOODIMG         VARCHAR2(300),
    OFFICIALURL     VARCHAR2(500),
    CREATEDAT       DATE DEFAULT SYSDATE,
    UPDATEDAT       DATE DEFAULT NULL 
    );
    
CREATE SEQUENCE petfood_seq
START WITH 1 INCREMENT BY 1
NOCACHE;



3. 영양소
--3. 영양소 외래키X
CREATE TABLE NUTRI(
    NUTRIENTID NUMBER PRIMARY KEY,
    NUTRIENTNAME VARCHAR2(100) NOT NULL,
    UNIT VARCHAR2(50) 
);


4. 라벨영양소
--4.라벨영양소 (FK) FOODID : PETFOOD(FOODID) / NUTRIENTID  : NUTRI(NUTRIENTID)
CREATE TABLE PETFOODNUTRI(
    FOODID      NUMBER NOT NULL,
    NUTRIENTID  NUMBER NOT NULL,
    AMOUNT      NUMBER
);

5. 영양소범위
--5.영양소범위 (FK) NUTRIENTID : NUTRI(NUTRIENTID)		
CREATE TABLE NUTRIRANGE (
    RANGEID      NUMBER          PRIMARY KEY,
    PETTYPEID    NUMBER          NOT NULL,
    NUTRIENTID   NUMBER          NOT NULL,
    MINVALUE     NUMBER          NOT NULL,
    MAXVALUE     NUMBER          NOT NULL,
    RANGELABEL   VARCHAR2(50)    NOT NULL
);

6. 관리자계정
--6. 관리자 계정
CREATE TABLE ADMIN (
  ADMINID        NUMBER          PRIMARY KEY,
  EMAIL          VARCHAR2(100) NOT NULL,
  PASSWORD       VARCHAR2(255) NOT NULL,
  ROLE           VARCHAR2(20) DEFAULT 'ADMIN',
  CREATEDAT      DATE DEFAULT SYSDATE
);
