
--1. 브랜드 외래키X
CREATE TABLE BRAND (
    BRANDID        NUMBER           PRIMARY KEY,
    BRANDNAME      VARCHAR2(100)    NOT NULL,
    COUNTRY        VARCHAR2(100), 
    ORIGIN         VARCHAR2(50),             
    BRANDINFO      VARCHAR2(500)

);
CREATE SEQUENCE BRAND_SEQ 
START WITH 1 INCREMENT BY 1
NOCACHE;

--로얄캐닌
--https://www.royalcanin.com/kr
INSERT INTO BRAND(BRANDID, BRANDNAME, COUNTRY, ORIGIN, BRANDINFO )
VALUES(BRAND_SEQ.NEXTVAL, '로얄캐닌', '프랑스', '해외', '건강에 대한 바른 집념, 로얄캐닌');

--힐스
--https://www.hillspet.co.kr/
INSERT INTO BRAND(BRANDID, BRANDNAME, COUNTRY, ORIGIN, BRANDINFO )
VALUES(BRAND_SEQ.NEXTVAL, '힐스', '미국', '해외', '힐스 펫 뉴트리션, 과학에 기반한 프리미엄 반려동물 사료');

--인스팅트
--http://www.instinctpetfood.co.kr/
INSERT INTO BRAND(BRANDID, BRANDNAME, COUNTRY, ORIGIN, BRANDINFO )
VALUES(BRAND_SEQ.NEXTVAL, '인스팅트', '미국', '해외', '생식에 기반을 둔 영양 인스팅트');

--오리젠
--https://apac.orijenpetfoods.com/ko-KR/homepage
INSERT INTO BRAND(BRANDID, BRANDNAME, COUNTRY, ORIGIN, BRANDINFO )
VALUES(BRAND_SEQ.NEXTVAL, '오리젠', '캐나다', '해외', '자연 유래 영양 성분');

--뉴트리플랜
--http://www.dongwonpet.com/
INSERT INTO BRAND(BRANDID, BRANDNAME, COUNTRY, ORIGIN, BRANDINFO )
VALUES(BRAND_SEQ.NEXTVAL, '뉴트리플랜', '한국', '국내', '냥이 보호자들이 선택한 브랜드');

--웰니스
--https://wellnesspet.kr/
INSERT INTO BRAND(BRANDID, BRANDNAME, COUNTRY, ORIGIN, BRANDINFO )
VALUES(BRAND_SEQ.NEXTVAL, '웰니스', '미국', '해외', '유한양행 사료, 웰니스');

COMMIT; 

--2.푸드 (FK) BRANDID : BFAND(BRANDID)
CREATE TABLE PETFOOD (
    FOODID          NUMBER          PRIMARY KEY,
    FOODNAME        VARCHAR2(100)   NOT NULL,
    BRANDID         NUMBER          NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    MAININGREDIENT  VARCHAR2(200)   NOT NULL,
    PETTYPEID       NUMBER           DEFAULT 1,
    PETTYPENAME     VARCHAR2(255)    DEFAULT '고양이',
    CATEGORY        VARCHAR2(50)    NOT NULL,
    PETAGEGROUP     VARCHAR2(50),
    ISGRAINFREE     CHAR(1)         CHECK (UPPER(ISGRAINFREE) IN ('Y','N')),
    CALORIE         NUMBER(5,1),
    FOODTYPE        VARCHAR2(20) DEFAULT '습식',
    FOODIMG         VARCHAR2(300),
    OFFICIALURL     VARCHAR2(500),
    CREATEDAT       DATE DEFAULT SYSDATE,
    UPDATEDAT       DATE DEFAULT NULL 
    );
    
CREATE SEQUENCE petfood_seq
START WITH 1 INCREMENT BY 1
NOCACHE;

--로얄캐닌 : 마더 앤 베이비캣
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 마더 앤 베이비캣', 1, '임신 말기부터 수유기의 어미 반려묘와 생후 4개월까지 반려묘의 건강에 도움을 주는 임신 및 성장기 영양 맞춤 사료',
        '닭', '일반', '키튼', 'N',
        443.7, '01001.png', 'https://www.royalcanin.com/kr/cats/products/retail-products/mother-%26-babycat-2544');

--조단백 32.0%이상, 조지방 23.0%이상, 칼슘 1.0%이상, 인 0.82%이상, 조회분 8.4%이하, 조섬유 2.8%이하, 수분 6.5%이하
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(1, 1, 32.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(1, 2, 23.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(1, 3, 2.8);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(1, 4, 8.4);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(1, 5, 1.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(1, 6, 0.82);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(1, 7, 6.5);


--로얄캐닌 : 키튼
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 키튼', 1, '생후 4개월 이후부터 12개월까지',
        '닭', '일반', '키튼', 'N',
        367.0, '01002.png', 'https://www.royalcanin.com/kr/cats/products/retail-products/kitten-2522');

--조단백 34.0%이상, 조지방 16.0%이상, 칼슘 0.99%이상, 인 0.87%이상, 조회분 8.9%이하, 조섬유 3.4%이하, 수분 6.5%이하
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(2, 1, 34.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(2, 2, 16.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(2, 3, 3.4);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(2, 4, 8.9);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(2, 5, 0.99);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(2, 6, 0.87);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(2, 7, 6.5);
    


--로얄캐닌 : 스테럴라이즈드
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 스테럴라이즈드', 1, '중성화를 한 생후 12개월 이후 반려묘의 체중관리에 도움을 주는 영양맞춤사료',
        '닭', '일반', '어덜트', 'N',
        352.4, '01003.png', 'https://www.royalcanin.com/kr/cats/products/retail-products/sterilised-37-2537');

--단백질 37%, 지방 12%, 조섬유 6.2%, 조회분 8.2%, NFE 31.1% 
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(3, 1, 37.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(3, 2, 12.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(3, 3, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(3, 4, 8.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(3, 5, 0.88);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(3, 6, 0.8);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(3, 7, 6.5);


--로얄캐닌 : 라이트웨이트케어
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 라이트웨이트케어', 1, '과체중 경향이 있는 생후 12개월 이후 반려묘의 건강한 체중 관리에 도움을 주는 건강기능사료',
        '닭',  '일반', '어덜트', 'N',
        352.4, '01004.png', 'https://www.royalcanin.com/kr/cats/products/retail-products/light-weight-care-2524');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
--단백질 40%, 조지방 10%, 조섬유 7.6%, 조회분 7.2%
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(4, 1, 40.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(4, 2, 10.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(4, 3, 7.6);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(4, 4, 7.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(4, 5, 0.96);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(4, 6, 0.72);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(4, 7, 6.5);



--로얄캐닌 : 인도어
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 인도어', 1, '생후 12개월 이후 활동량이 적은 실내 반려묘의 건강과 변량, 냄새감소에 도움을 주는 영양맞춤사료',
        '닭', '일반', '어덜트', 'N',
        377.6, '01005.png', 'https://www.royalcanin.com/kr/cats/products/retail-products/indoor-27-2529');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
--단백질 27%, 지방 13%, 조섬유 4%, 조회분 7.3%,
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(5, 1, 27.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(5, 2, 13.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(5, 3, 4.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(5, 4, 7.3);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(5, 5, 0.88);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(5, 6, 0.64);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(5, 7, 6.5);
    

--로얄캐닌 : 캣 에이징 11+
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 캣 에이징 11+', 1, '11세 이상의 반려묘를 위한 최적의 영양맞춤사료',
        '닭', '일반', '시니어', 'N',
        400.3, '01006.png', 'https://www.royalcanin.com/kr/cats/products/retail-products/ageing-11%2B-2561');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
--조단백 28.0% 이상, 조지방 15.0% 이상, 칼슘 0.63% 이상, 인 0.54% 이상, 조섬유 3.9% 이하, 조회분 6.7% 이하, 수분 6.5%
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(6, 1, 28.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(6, 2, 15.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(6, 3, 3.9);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(6, 4, 6.7);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(6, 5, 0.63);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(6, 6, 0.54);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(6, 7, 6.5);


--로얄캐닌 : 캣 하이포알러제닉
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 캣 하이포알러제닉', 1, '반려묘의 알러지 피부염 증상 관리에 도움을 주는 수의사 처방 전용 제품',
        '닭',  '처방식', '어덜트', 'N',
        409.0, '01007.png', 'https://www.royalcanin.com/kr/cats/products/vet-products/hypoallergenic-3902');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(7, 1, 25.5);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(7, 2, 20.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(7, 3, 3.7);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(7, 4, 6.6);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(7, 5, 0.7);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(7, 6, 0.6);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(7, 7, 5.5);


--로얄캐닌 : 캣 가스트로인테스티널
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 캣 가스트로인테스티널', 1, '반려묘의 위장관 질환 관리에 도움을 주는 수의사 처방 전용 제품',
        '닭', '처방식', '어덜트', 'N',
        409.0, '01008.png', 'https://www.royalcanin.com/kr/cats/products/vet-products/gastrointestinal-3905');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(8, 1, 32.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(8, 2, 22.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(8, 3, 4.8);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(8, 4, 6.6);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(8, 5, 1.12);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(8, 6, 1.02);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(8, 7, 5.5);


--로얄캐닌 : 캣 유리너리 S/O
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 캣 유리너리 S/O', 1, '성묘의 스트루바이트 결석관리를 위해 급여',
        '닭', '처방식', '어덜트', 'N',
        387.0, '01009.png', 'https://www.royalcanin.com/kr/cats/products/vet-products/urinary-so-3901');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(9, 1, 34.5);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(9, 2, 15.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(9, 3, 2.9);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(9, 4, 6.6);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(9, 5, 0.9);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(9, 6, 0.9);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(9, 7, 5.5);



--로얄캐닌 : 캣 헤파틱
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 캣 헤파틱', 1, '반려묘의 간질환 관리에 도움을 주는 수의사 처방 전용 제품',
        '닭',  '처방식', '어덜트', 'N',
        413.6, '01010.png', 'https://www.royalcanin.com/kr/cats/products/vet-products/hepatic-4012');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(10, 1, 26.1);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(10, 2, 22.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(10, 3, 4.9);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(10, 4, 6.6);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(10, 5, 0.6);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(10, 6, 0.6);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(10, 7, 5.5);


--로얄캐닌 : 캣 레날 스페셜
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 캣 레날 스페셜', 1, '반려묘의 신장 질환 관리에 도움을 주는 수의사 처방 전용 제품',
        '돼지', '처방식', '어덜트', 'N',
        391.9, '01011.png', 'https://www.royalcanin.com/kr/cats/products/vet-products/renal-special-3949');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(11, 1, 26.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(11, 2, 17.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(11, 3, 4.8);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(11, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(11, 5, 0.63);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(11, 6, 0.45);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(11, 7, 5.5);        


--로얄캐닌 : 캣 다이아베틱
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '로얄캐닌 캣 다이아베틱', 1, '반려묘의 당뇨병 관리에 도움을 주는 수의사 처방 전용 제품',
        '닭', '처방식', '어덜트', 'N',
        385.2, '01012.png', 'https://www.royalcanin.com/kr/cats/products/vet-products/diabetic-3906');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(12, 1, 46.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(12, 2, 12.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(12, 3, 4.1);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(12, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(12, 5, 1.04);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(12, 6, 0.9);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(12, 7, 5.5);        

        

-------------------------------------------------------------------------

--힐스 : 키튼 치킨 레시피
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 키튼 치킨 레시피', 2, '평생 건강을 위한 5가지 핵심 영양소 지원',
        '닭', '일반', '키튼', 'N',
        407.6, '02001.png', 'https://www.hillspet.co.kr/cat-food/sd-feline-kitten-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(13, 1, 38.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(13, 2, 22.9);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(13, 3, 1.8);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(13, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(13, 5, 1.44);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(13, 6, 1.2);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(13, 7, 5.5);        

--힐스 : 어덜트 인도어 치킨 레시피
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 어덜트 인도어 치킨 레시피', 2, '실내묘에게 요구되는 칼로리 제공 및 아름다운 모질에 도움',
        '닭', '일반', '어덜트', 'N',
        349.2, '02002.png', 'https://www.hillspet.co.kr/cat-food/sd-feline-adult-indoor-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(14, 1, 36.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(14, 2, 14.7);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(14, 3, 8.5);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(14, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(14, 5, 0.92);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(14, 6, 0.77);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(14, 7, 5.5);        



--힐스 : 어덜트 퍼펙트 다이제스천
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 어덜트 퍼펙트 다이제스천', 2, '사이언스 다이어트의 혁신적인 영양이 소화기와 마이크로바이옴의 건강을 돕습니다.',
        '연어', '일반', '어덜트', 'N',
        384.4, '02003.png', 'https://www.hillspet.co.kr/cat-food/sd-feline-adult-perfect-digestion-salmon-oats-brown-rice-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(15, 1, 35.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(15, 2, 18.7);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(15, 3, 2.3);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(15, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(15, 5, 0.98);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(15, 6, 0.78);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(15, 7, 5.5);        


--힐스 : 어덜트 11+ 치킨 레시피
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 어덜트 11+ 치킨 레시피', 2, '11세 이상 고양이의 두뇌 건강과 아름다운 모질에 도움',
        '닭', '일반', '시니어', 'N',
        404.4, '02004.png', 'https://www.hillspet.co.kr/cat-food/sd-feline-adult-11-plus-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(16, 1, 32.6);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(16, 2, 21.5);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(16, 3, 1.4);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(16, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(16, 5, 0.9);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(16, 6, 0.68);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(16, 7, 5.5);   


--힐스 : c/d 멀티케어 스트레스 치킨
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 c/d 멀티케어 스트레스 치킨', 2, '반려묘의 스트레스 감소에 도움이 되는 원료의 첨가로 비뇨기 관리에 도움을 줍니다.',
        '닭', '처방식', '어덜트', 'N',
        384.4, '02005.png', 'https://www.hillspet.co.kr/cat-food/pd-cd-multicare-feline-stress-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(17, 1, 33.9);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(17, 2, 16.1);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(17, 3, 1.0);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(17, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(17, 5, 0.81);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(17, 6, 0.67);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(17, 7, 5.5);   


--힐스 : GI 바이옴 스트레스 
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 GI 바이옴 스트레스', 2, '소화 불량을 겪는 고양이의 스트레스를 줄이는 데 도움이 되는 독자적 제조법으로 만들어진 맛있는 영양 사료입니다.',
        '닭', '처방식', '어덜트', 'N',
        380.7, '02006.png', 'https://www.hillspet.co.kr/cat-food/pd-gastrointestinal-biome-feline-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(18, 1, 37.3);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(18, 2, 17.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(18, 3, 3.3);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(18, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(18, 5, 0.75);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(18, 6, 0.72);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(18, 7, 5.5);   


--힐스 : i/d 반려묘용 건사료
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 i/d 반려묘용 건사료', 2, '힐스 프리스크립션 다이어트 i/d 반려묘용 건사료는 소화기 건강을 위한 사료입니다.',
        '닭', '처방식', '어덜트', 'N',
        393.4, '02007.png', 'https://www.hillspet.co.kr/cat-food/pd-id-feline-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(19, 1, 37.4);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(19, 2, 20.1);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(19, 3, 1.9);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(19, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(19, 5, 1.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(19, 6, 0.79);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(19, 7, 5.5);   


--힐스 : k/d 반려묘용 건사료(오션피쉬)
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 k/d 반려묘용 건사료(오션피쉬)', 2, '맛있고 임상적으로 증명된 영양이 신장의 주요 기능을 보호하고 식욕 증진을 돕습니다.',
        '생선', '처방식', '어덜트', 'N',
        408.4, '02008.png', 'https://www.hillspet.co.kr/cat-food/pd-kd-feline-with-ocean-fish-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(20, 1, 29.3);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(20, 2, 22.5);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(20, 3, 3.1);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(20, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(20, 5, 0.79);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(20, 6, 0.51);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(20, 7, 5.5);   



--힐스 : ONC 케어 반려묘용 건사료
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 ONC 케어 반려묘용 건사료', 2, '암에 걸린 반려묘을 위해 임상 영양학적으로 설계된 처방사료입니다.',
        '닭', '처방식', '어덜트', 'N',
        581.0, '02009.png', 'https://www.hillspet.co.kr/cat-food/pd-feline-onc-on-care-chicken-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(21, 1, 40.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(21, 2, 25.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(21, 3, 1.9);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(21, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(21, 5, 0.9);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(21, 6, 0.75);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(21, 7, 5.5);   


--힐스 : t/d 반려묘용 건사료
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 t/d 반려묘용 건사료', 2, '치태와 치석의 형성률을 감소시키고 잇몸선까지 닦는 것이 임상적으로 증명된 사료입니다.',
        '닭', '처방식', '어덜트', 'N',
        352.0, '02010.png', 'https://www.hillspet.co.kr/cat-food/pd-td-feline-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(22, 1, 35.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(22, 2, 17.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(22, 3, 8.3);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(22, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(22, 5, 1.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(22, 6, 0.79);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(22, 7, 5.5);   


--힐스 : w/d 멀티 베네핏 반려묘용 건사료
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 w/d 멀티 베네핏 반려묘용 건사료', 2, '비뇨기 건강, 소화기 건강, 혈당 관리 그리고 체중 관리와 같이 다양한 방면에 도움을 줄 목적으로 특별히 개발된 제품입니다. ',
        '닭', '처방식', '어덜트', 'N',
        322.5, '02011.png', 'https://www.hillspet.co.kr/cat-food/pd-wd-feline-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(23, 1, 41.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(23, 2, 9.4);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(23, 3, 6.2);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(23, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(23, 5, 1.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(23, 6, 0.84);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(23, 7, 5.5);   


--힐스 :y/d 반려묘용 건사료
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 y/d 반려묘용 건사료', 2, '갑상선 기능 항진증을 앓고 있는 반려묘를 지원합니다.',
        '닭', '처방식', '어덜트', 'N',
        400.5, '02012.png', 'https://www.hillspet.co.kr/cat-food/pd-yd-feline-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(24, 1, 35.4);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(24, 2, 22.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(24, 3, 3.8); 
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(24, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(24, 5, 0.69);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(24, 6, 0.97);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(24, 7, 5.5);   


--힐스 : z/d 반려묘용 건사료
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 z/d 반려묘용 건사료', 2, '가수분해 단백질로 제조되어, 반려묘의 식이 역반응으로 인한 가려움, 소화 문제 등을 줄이는 데 도움을 줍니다.',
        '닭', '처방식', '어덜트', 'N',
        384.7, '02013.png', 'https://www.hillspet.co.kr/cat-food/pd-zd-feline-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(25, 1, 34.3);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(25, 2, 17.3);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(25, 3, 1.4);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(25, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(25, 5, 0.75);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(25, 6, 0.59);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(25, 7, 5.5);   


--힐스 :메타볼릭 반려묘용 건사료
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '힐스 메타볼릭 반려묘용 건사료', 2, '반려묘의 고유한 신진대사를 활성화하여 빠르고 자연스럽게 체중을 감량하도록 도와줍니다.',
        '닭', '처방식', '어덜트', 'N',
        339.8, '02014.png', 'https://www.hillspet.co.kr/cat-food/pd-metabolic-feline-dry');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(26, 1, 38.6);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(26, 2, 13.4);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(26, 3, 9.8);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(26, 4, 6.2);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(26, 5, 0.76);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(26, 6, 0.77);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(26, 7, 5.5);   

-------------------------------------------------------------------------------------------------------

--인스팅트:오리지날 생식본능 캣 키블
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '인스팅트 오리지날 생식본능 캣 키블', 3, '인스팅트 오리지날 생식본능 캣 키블은 AAFCO의 영양 기준을 충족하여 만들어진 전연령용 제품입니다.',
        '닭', '일반', '어덜트', 'Y',
        430.0, '03001.png', 'http://www.instinctpetfood.co.kr/new_products/orig_cat_ch.jsp');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(27, 1, 41.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(27, 2, 21.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(27, 3, 3.0);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(27, 4, 6.2);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(27, 5, 0.76);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(27, 6, 0.77);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(27, 7, 9.0);   


--인스팅트:오리지날 연어 캣 키블
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '인스팅트 오리지날 연어 캣 키블', 3, '인스팅트 오리지날 연어 캣 키블은 AAFCO의 영양 기준을 충족하여 만들어진 전연령용 제품입니다.',
        '연어', '일반', '어덜트', 'Y',
        447.0, '03002.png', 'http://www.instinctpetfood.co.kr/new_products/orig_cat_salmon.jsp');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(28, 1, 42.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(28, 2, 18.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(28, 3, 3.0);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(28, 4, 6.2);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(28, 5, 0.76);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(28, 6, 0.77);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(28, 7, 9.0);  


--인스팅트:오리지날 토끼고기 캣 키블
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '인스팅트 오리지날 토끼고기 캣 키블', 3, '인스팅트 오리지날 토끼고기 캣 키블은 AAFCO의 영양 기준을 충족하여 만들어진 전연령용 제품입니다.',
        '토끼', '일반', '어덜트', 'Y',
        434.6, '03003.png', 'http://www.instinctpetfood.co.kr/new_products/orig_cat_rabbit.jsp');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(29, 1, 40.5);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(29, 2, 22.5);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(29, 3, 3.0);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(29, 4, 6.2);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(29, 5, 0.76);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(29, 6, 0.77);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(29, 7, 9.0);  


--인스팅트:인스팅트 LID 칠면조고기 캣 키블
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '인스팅트 LID 칠면조고기 캣 키블', 3, '인스팅트 LID 칠면조고기 캣 키블은 AAFCO의 영양 기준을 충족하여 만들어진 성묘용 제품입니다.',
        '칠면조', '일반', '어덜트', 'Y',
        407.0, '03004.png', 'http://www.instinctpetfood.co.kr/new_products/lid_cat_turkey.jsp');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(30, 1, 35.5);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(30, 2, 16.5);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(30, 3, 4.0);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(30, 4, 6.2);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(30, 5, 0.76);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(30, 6, 0.77);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(30, 7, 9.0);  

--인스팅트:인스팅트 LID 토끼고기 캣 키블
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '인스팅트 LID 토끼고기 캣 키블', 3, '인스팅트 LID 토끼고기 캣 키블은 AAFCO의 영양 기준을 충족하여 만들어진 성묘용 제품입니다.',
        '토끼', '일반', '어덜트', 'Y',
        389.0, '03005.png', 'http://www.instinctpetfood.co.kr/new_products/lid_cat_rabbit.jsp');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(31, 1, 35.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(31, 2, 19.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(31, 3, 5.5);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(31, 4, 6.2);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(31, 5, 0.76);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(31, 6, 0.77);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(31, 7, 9.0);  


--인스팅트:인스팅트 LID 연어 캣 키블
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '인스팅트 LID 연어 캣 키블', 3, '인스팅트 LID 연어 캣 키블은 AAFCO의 영양 기준을 충족하여 만들어진 성묘용 제품입니다.',
        '연어', '일반', '어덜트', 'Y',
        389.0, '03006.png', 'http://www.instinctpetfood.co.kr/new_products/lid_cat_salmon.jsp');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(32, 1, 37.4);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(32, 2, 17.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(32, 3, 3.0);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(32, 4, 6.2);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(32, 5, 0.76);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(32, 6, 0.77);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(32, 7, 9.0);  


--인스팅트:인스팅트 얼티밋 프로틴 치킨 캣 키블
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '인스팅트 얼티밋 프로틴 치킨 캣 키블', 3, '인스팅트 얼티밋 프로틴 캣 키블은 AAFCO의 영양 기준을 충족하여 만들어진 전연령용 제품입니다.',
        '닭', '일반', '어덜트', 'Y',
        447.0, '03007.png', 'http://www.instinctpetfood.co.kr/new_products/ult_cat_ch.jsp');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(33, 1, 47.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(33, 2, 17.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(33, 3, 3.0);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(33, 4, 6.2);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(33, 5, 0.76);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(33, 6, 0.77);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(33, 7, 10.0);  


--인스팅트:인스팅트 얼티밋 프로틴 오리고기 캣 키블
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '인스팅트 얼티밋 프로틴 오리고기 캣 키블', 3, '인스팅트 얼티밋 프로틴 오리고기 캣 키블은 AAFCO의 영양 기준을 충족하여 만들어진 전연령용 제품입니다.',
        '오리', '일반', '어덜트', 'Y',
        451.0, '03008.png', 'http://www.instinctpetfood.co.kr/new_products/ult_cat_duck.jsp');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 1, 47.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 2, 17.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 3, 3.0);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 4, 6.2);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 5, 0.76);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 6, 0.77);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 7, 10.0);  

--인스팅트:인스팅트 BE 내추럴 캣 키블
INSERT INTO PETFOOD(FOODID, FOODNAME, BRANDID, DESCRIPTION, 
                    MAININGREDIENT , CATEGORY, PETAGEGROUP, ISGRAINFREE, 
                    CALORIE, FOODIMG, OFFICIALURL)
VALUES(PETFOOD_SEQ.NEXTVAL, '인스팅트 BE 내추럴 캣 키블', 3, '인스팅트 BE 내추럴 캣 키블은 AAFCO의 영양 기준을 충족하여 만들어진 전연령용 제품입니다.',
        '닭', '일반', '어덜트', 'N',
        389.9, '03009.png', 'http://www.instinctpetfood.co.kr/new_products/be_cat_ch.jsp');

--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 1, 36.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 2, 18.0);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 3, 4.0);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 4, 6.2);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 5, 0.76);
--INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 6, 0.77);
INSERT INTO PETFOODNUTRI(FOODID, NUTRIENTID, AMOUNT) VALUES(34, 7, 9.0);  


        
--3. 영양소 외래키X
CREATE TABLE NUTRI(
    NUTRIENTID NUMBER PRIMARY KEY,
    NUTRIENTNAME VARCHAR2(100) NOT NULL,
    UNIT VARCHAR2(50) 
);


--4.라벨영양소 (FK) FOODID : PETFOOD(FOODID) / NUTRIENTID  : NUTRI(NUTRIENTID)
CREATE TABLE PETFOODNUTRI(
    FOODID      NUMBER NOT NULL,
    NUTRIENTID  NUMBER NOT NULL,
    AMOUNT      NUMBER
);

--5.영양소범위 (FK) NUTRIENTID : NUTRI(NUTRIENTID)		
CREATE TABLE NUTRIRANGE (
    RANGEID      NUMBER          PRIMARY KEY,
    PETTYPEID    NUMBER          NOT NULL,
    NUTRIENTID   NUMBER          NOT NULL,
    MINVALUE     NUMBER          NOT NULL,
    MAXVALUE     NUMBER          NOT NULL,
    RANGELABEL   VARCHAR2(50)    NOT NULL
);

--6. 관리자 계정
CREATE TABLE ADMIN (
  ADMINID        NUMBER          PRIMARY KEY,
  EMAIL          VARCHAR2(100) NOT NULL,
  PASSWORD       VARCHAR2(255) NOT NULL,
  ROLE           VARCHAR2(20) DEFAULT 'ADMIN',
  CREATEDAT      DATE DEFAULT SYSDATE
);


---------------------------------------------------
--영양소 단위
--조단백, 조지방, 조섬유, 조회분, 칼슘, 인, 수분
---------------------------------------------------
INSERT INTO NUTRI VALUES (1, '조단백', '%');
INSERT INTO NUTRI VALUES (2, '조지방', '%');
INSERT INTO NUTRI VALUES (3, '조섬유', '%');
INSERT INTO NUTRI VALUES (4, '조회분', '%');
INSERT INTO NUTRI VALUES (5, '칼슘', '%');
INSERT INTO NUTRI VALUES (6, '인', '%');
INSERT INTO NUTRI VALUES (7, '수분', '%');

---------------------------------------------------
--영양소 범위(추가 검증 필요)
---------------------------------------------------
-- 저단백 (신장/시니어)
INSERT INTO NUTRIRANGE VALUES (1, 1, 1, 18, 26, '저단백');

-- 중단백 (일반 성묘 메인)
INSERT INTO NUTRIRANGE VALUES (2, 1, 1, 27, 34, '중단백');

-- 고단백 (활동량↑, 키튼/컨셉사료)
INSERT INTO NUTRIRANGE VALUES (3, 1, 1, 35, 42, '고단백');

-- 저지방
INSERT INTO NUTRIRANGE VALUES (4, 1, 2, 8, 12, '저지방');

-- 고칼슘 (성장기 기준)
INSERT INTO NUTRIRANGE VALUES (6, 1, 5, 1.4, 1.8, '고칼슘');

-- 저인 (신장 케어 전용)
INSERT INTO NUTRIRANGE VALUES (5, 1, 6, 0.4, 0.7, '저인');

-- 중인 (일반 성묘 대다수)
INSERT INTO NUTRIRANGE VALUES (7, 1, 6, 0.8, 1.2, '중인');

-- 고인 (키튼/고단백 컨셉)
INSERT INTO NUTRIRANGE VALUES (8, 1, 6, 1.3, 1.8, '고인');


COMMIT;